[package]
name = "Hooks"
version = "0.1.0"
authors = ["Steven Black <steveb@stevenblack.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.196", features = ["derive"] }
